name: Publish Docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/publish-docs.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.5
      - name: Install dependencies
        run: cd docs && pnpm install
      - name: Build & Deploy Worker
        run: pnpm run deploy