name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
        
    - name: Install dependencies
      run: |
        go install github.com/go-task/task/v3/cmd/task@latest
        go install github.com/swaggo/swag/cmd/swag@latest
        go install github.com/google/wire/cmd/wire@latest
        
    - name: Build taskw binary for tests
      run: |
        mkdir -p bin
        go build -o bin/taskw main.go
        chmod +x bin/taskw
        
    - name: Run tests
      run: go test -v ./...
   
